### ISSUE TITLE
Headers , Body , Cookies  は英単語のままの方が直感的では

### ISSUE THREAD

**Issue by s0hide** [postmanlabs/postman-japanese-ea#10]
### 問題の詳細

Headers , Body , Cookies  は、
翻訳せず、英単語のままでどうでしょうか？ そのほうが、むしろ直感的、わかりやすい気がします。
ブラウザのデバッグモード、ブラウザの設定画面でも、英単語のままだったりするので、
特に違和感はなく受け入れられると思います。

### 現在の表記

ヘッダー、ボディ、クッキー

### 提案する表記

Headers , Body , Cookies

### スクリーンショット／動画

<img width="1609" alt="スクリーンショット 2023-10-26 16 38 40" src="https://github.com/postmanlabs/postman-japanese-ea/assets/144641648/2638718e-9a9b-4af8-9f3e-4cb9de86147a">

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.9-231025-0520

**Comment by nagix** [comment]
ご提案ありがとうございます。Cookiesに関しては、専門性が高く英語のまま利用するのが一般的ですので、そのように変更したいと思います（ただし、理解をしやすくするために単数形のCookieとします）。Headers、Bodyに関しては、ヘッダー、ボディの用語は一般に使われておりますので、現状のままにする方針です。
