### ISSUE TITLE
Pretty の和訳

### ISSUE THREAD

**Issue by s0hide** [postmanlabs/postman-japanese-ea#11]
### 問題の詳細

現在、Pretty が整形となっているところ、
整形表示
ではいかがでしょうか？

### 現在の表記

整形

### 提案する表記

整形表示

### スクリーンショット／動画

<img width="260" alt="スクリーンショット 2023-10-26 17 14 37" src="https://github.com/postmanlabs/postman-japanese-ea/assets/144641648/0165f47d-bcdb-4caf-9e8f-1e311333a0f9">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.9-231025-0520

**Comment by nagix** [comment]
ご提案ありがとうございます。他のタブで表示されている未加工（こちらは Raw に変更予定です）、プレビューも、厳密には「表示」が後につくところを省略している意図がありますので、レベル感を統一するために「整形」のままにしたいと考えております。
