### ISSUE TITLE
Explore の和訳

### ISSUE THREAD

**Issue by s0hide** [postmanlabs/postman-japanese-ea#12]
### 問題の詳細

Explore の和訳は、
探索でも良いですが、
さらに詳しく
みたいな表記も良いのでは、と思いました。

### 現在の表記

探索

### 提案する表記

さらに詳しく

### スクリーンショット／動画

<img width="412" alt="スクリーンショット 2023-10-26 17 17 46" src="https://github.com/postmanlabs/postman-japanese-ea/assets/144641648/70022fdb-7676-44c5-844c-413a25d8c754">

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.9-231025-0520

**Comment by nagix** [comment]
ご提案ありがとうございます。「探索」はやや直感的ではないところではありますが、一方で「さらに詳しく」という表記は通常何らかの概要や限定された項目のリストのある場所で詳細情報への誘導を促すために使用されますので、メインメニューの表記としては適していないと考えます。このメニュー項目のジャンプ先は、PostmanパブリックAPIネットワーク（APIカタログ）であり、カタログの中を自由に見て回ってもらうことを意図しておりますので、「探索」という用語を使用しています。
