### ISSUE TITLE
「選択」ボタンのレイアウトが崩れている

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#13]
### 問題の詳細

設定メニューで「選択」ボタンのレイアウトに問題が発生し、ズームイン・アウトの状態に関係なく「選択」のテキストが不適切に改行されています。

### 再現ステップ

1. 設定を開く
2. 「一般」>「作業ディレクトリ」>「場所」

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/78534785-9304-4595-8d4d-6dd386e7bdae)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.6-231017-0734

### その他のコメントやコンテキスト

優先度が高くないと思いますが、調整行えば綺麗に表示できます。
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/9026e056-3a58-4761-8b71-d17fc72849ce)

**Comment by nagix** [comment]
ご指摘ありがとうございます。バグ登録をしましたので、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
