### ISSUE TITLE
「デフォルトのドキュメントエディター」のテキストレイアウトが崩れている

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#14]
### 問題の詳細

設定メニューで「デフォルトのドキュメントエディター」のテキストのレイアウトに問題が発生し、ズームイン・アウトの状態に関係なく「デフォルトのドキュメントエディター」のテキストが不適切に改行されています。

### 再現ステップ

1. 設定を開く
2. 「一般」>「ユーザーインターフェース」

### スクリーンショット／動画

![Screenshot 2023-10-27 at 14 40 38](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/9916abda-719a-4076-8854-bcaa1b338cf7)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.6-231017-0734

### その他のコメントやコンテキスト

日本語あるあるですが、一文字でも改行されてしまう現象です。marginなど微調整すれば綺麗に表示できます。

https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/3de402b8-4037-4d82-9eaa-6c8207b68ea6

**Comment by nagix** [comment]
ご指摘ありがとうございます。バグ登録をしましたので、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
