### ISSUE TITLE
不要な「...」が表示されている

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#15]
### 問題の詳細

英語版では「...」表示されないのに日本語版では「...」表示されてしまう。

### 現在のテキスト

「データのエクスポートをリクエスト...」、「ファイルをアプローど...」、「データを移行...」

### スクリーンショット／動画

日本語版
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/af1c135e-4ad5-49df-99e5-f4c397f0a1cb)

英語版
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/de694b2e-923c-4604-b91c-f1b92e6f81a7)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.7-ui-231020-0706

### その他コメントやコンテキスト

英語版でも「...」表示される場合がある(下のスクリーンショット)ので、おそらく本件はちょっとした翻訳ミスと思われます。
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/519aa1b9-8ed0-4472-951f-6008d7a90893)

**Comment by nagix** [comment]
ご指摘ありがとうございます。「...」は不要であるため削除します。また、「ファイルをアップロード」はより適切な「データファイルをインポート」に変更予定です。
