### ISSUE TITLE
「Scratch Pad Data」部分が英語のまま

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#16]
### 問題の詳細

「設定」 > 「データ」>「Scratch Pad Data」テキストが英語のまま残っており、翻訳が行われていない状態です。

### 現在のテキスト

"Scratch Pad Data", "Export Scratch Pad data Export all your scratch Pad data into a single dump file.", "Export Scratch Pad Data"

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/6bd19680-5a0b-4edb-9532-4af546e9534c)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.7-ui-231020-0706

### その他コメントやコンテキスト

ウエブアプリでは存在されない機能ですので、おそらく見落としたかもしれない。

**Comment by nagix** [comment]
ご指摘ありがとうございます。上記の部分はすでに翻訳済みで、次のアップデートで対応予定です。
