### ISSUE TITLE
「Postman デスクトップエージェントを使用ください」ボタンのテキストのレイアウトが2行になっている

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#17]
### 問題の詳細

- 「設定」>「証明書」
- 「設定」>「プロクシー」

の2箇所で表示されています。

### 再現ステップ

1. 設定を開く
2. 「証明書」と「プロクシー」を選ぶ

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/8d810ba7-2b4b-4dca-8e0f-0a940986e7bc)

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-231026-1127

### その他のコメントやコンテキスト

直感的ですが1行にすればスッキリな画面になります。

https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/0021d72f-3497-44bf-8ec9-e2d741be0aa3

**Comment by nagix** [comment]
ご指摘ありがとうございます。バグ登録をしましたので、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
