### ISSUE TITLE
HTTPの説明文で「HTML」と翻訳されている

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#18]
### 問題の詳細

新規ワークスペースを作成する時に出てくるダイアログで「HTTP」をマウスオーバーすると説明文が(HTML)になっている

### 現在のテキスト

Hypertext Transfer Protocol (HTML) は、

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/83f20998-9d65-41f6-a383-a060cd0182f4)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-ui-231026-1128

### その他コメントやコンテキスト

英語版を確認したところ(HTTP)が正しい。
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/47c3ef2f-49ff-4d17-b4d8-97790af43bdd)

**Comment by nagix** [comment]
ご指摘ありがとうございます。次回のアップデートで修正予定です。
