### ISSUE TITLE
【ワークスペース｜インポート】不要な"Or select"が表示されている

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#19]
### 問題の詳細

ワークスペースをインポートする時、ダイアログボックスのテキストが不完全な翻訳になっている。
"Or select" 消せば本件は解決になるかと思います。

### 現在のテキスト

Or select ファイル or フォルダを選択ください

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/f63985c4-a911-42b2-b44f-a55d971e78e3)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-ui-231026-1128

### その他コメントやコンテキスト

英語版を添付させていただきます。
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/6a931e36-2bf8-4453-91fb-7a1a21ef53d0)

**Comment by rikosaita** [comment]
「ファイル or フォルダ」の「or」も適切な翻訳が必要になります。

**Comment by nagix** [comment]
「もしくはファイルまたはフォルダーを選択してください」のように修正予定です。
