### ISSUE TITLE
【ワークスペース】「公開範囲のフィルター」のレイアウトが崩れている

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#20]
### 問題の詳細

「チーム」以外の「公開範囲」フィルターのテクストボックスレイアウトが崩れる。

- 「すべて」
- 「パーソナル」
- 「プライベート」
- 「パートナー」
- 「パブリック」

### 再現ステップ

1. 「ワークスペース」>「すべてのワークスペースを見る」を開く
2. 「公開範囲」の各フィルターを選択

### スクリーンショット／動画

「すべて」を選択の場合
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/8f3f0191-ad7c-46d9-b125-08c4f513ac82)
「パーソナル」を選択の場合
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/08f2d67b-c72b-448d-8f43-f7ddcc9fa263)
「プライベート」を選択の場合
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/afc2e771-ef69-4515-b03b-b9346606322a)
「パートナー」を選択の場合
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/4135e9e0-f858-4bfd-856c-e9ac9dbc59d9)
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/f665e8a6-6353-4ff7-976f-565bcc6d4d8a)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-ui-231026-1128

### その他のコメントやコンテキスト

一応「チーム」を選択の場合のスクリーンショットを添付します。
![Screenshot 2023-10-27 at 20 41 13](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/36349f84-24e5-4e8e-a8b1-f32d655920fe)

英語版はテキストの長さにより自動調整のようです。

**Comment by nagix** [comment]
ご指摘ありがとうございます。バグ登録をしましたので、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
