### ISSUE TITLE
【歴史】ワークスペース編集許可がない場合、翻訳がない

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-japanese-ea#21]
### 問題の詳細

ワークスペース編集の許可がない状態で「歴史」のタブをクリックすると、翻訳がない

**再現ステップ**
1. 編集許可のないワークスペースにアクセス
（例：[Hugging Face公共ワークスペース](https://www.postman.com/postman-student-programs/workspace/hugging-face-inference-api-free/overview)）
2. 「歴史」タブをクリック

### 現在のテキスト

You don't have permission to view history // Only team members can view history of this workspace

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/c7fbc144-05bd-4609-87b2-dca22fe689bb)

### Postman プラットフォーム

両方

### オペレーティング システム

MacOS

### Postman バージョン

10.19.10

**Comment by nagix** [comment]
ご指摘ありがとうございます。バグ登録をしましたので、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
