### ISSUE TITLE
【ワークスペース設定】リンク、内容が翻訳されていない

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-japanese-ea#24]
### 問題の詳細

「ワークスペース設定」のリンクも内容も、ほとんど翻訳されていない状態です

「Private API Networkに追加」は翻訳されているが、Configure sidebarやワークスペース削除などそのほか基本的なワークスペース管理機能が翻訳されていなく、新規ユーザーに混乱を招くかも

**再現ステップ**
1.　ワークスペースにアクセス
2.  Workspace Settingsをクリック

### 現在のテキスト

Workspace settings // Visibility // People in this workspace // Configure sidebar // Delete workspace

### スクリーンショット／動画

<img width="1336" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/a89ca953-ec38-483b-8635-181acc986f40">

<img width="743" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/1238bfeb-0af4-4a87-a08b-63e125eb9ebb">

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘ありがとうございます。本件 #23 と同様の事象としてバグ登録させていただきました。

関連 issue: https://github.com/postmanlabs/postman-japanese-ea/issues/23

**Comment by nagix** [comment]
次のアップデートで修正予定です。
