### ISSUE TITLE
【コレクション】リクエストのないコレクションにデフォルトのメッセージは英語のまま「collection」

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-japanese-ea#25]
### 問題の詳細

空のコレクションを作るときに、リクエストを追加する前状態の表示に英語が混ざっている

### 再現ステップ
1. 新規コレクションを作成

### 現在の表記

このcollectionは空です

### 提案する表記

このコレクションは空です

### スクリーンショット／動画

<img width="300" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/170925f3-6402-4304-a2c4-70036d3c1db6">

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘頂きありがとうございます。ご指摘の通り"collection"部分も翻訳されるべきですので、バグとして登録させていただきました。また更新がありましたら本issueにてアップデート差し上げます 🙇‍♂️

**Comment by nagix** [comment]
次のアップデートで修正予定です。
