### ISSUE TITLE
【コレクション】フォーク作成画面にCollectionはあっちこっち英語のまま

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-japanese-ea#26]
### 問題の詳細

コレクションのフォーク作成画面に「Create a fork」のタブ名が翻訳されていなく、ページ内容にもあっちこっち「collection」が散らばっている

### 再現ステップ
1. コレクションから「フォークを作成」をクリック

### 現在のテキスト

Create a fork // collection

### スクリーンショット／動画

<img width="1065" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/c69274c3-93b5-4374-b8e0-caa21bf53f74">

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘頂きありがとうございます。内容について確認させていただき、対応方針について検討させていただきます。決まり次第アップデートいたします。

**Comment by yokawasa** [comment]
バグとして登録させていただきました。更新がありましたら本issueにてご連絡します

**Comment by nagix** [comment]
次のアップデートで修正予定です。
