### ISSUE TITLE
【ワークスペース】ワークスペースの作成失敗時のアラートメッセージが英語のまま

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#30]
### 問題の詳細

ワークスペースの作成失敗時のアラートメッセージが英語のままで、翻訳が行われていない状態です。

ステップ: パブリックワークスペースを作成時、名前が日本語のみ（「あ」）入力する > 「作成」ボタンを押す

### 現在のテキスト

Unable to create the workspace

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/8150858f-e97f-4324-b984-efa617bda345)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-ui-231026-1128

**Comment by yokawasa** [comment]
ご指摘ありがとうございます。バグとして登録させていただきました、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
