### ISSUE TITLE
Workspace settings で複数の英語ラベルが残っています

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#31]
### 問題の詳細

複数のラベルが英語のままです。
- Workspaceの概要タブ上の ”Workspace Settings"
- Workspace settings 画面上の複数のラベル

「現在のテキスト」には1つだけ入れておきます。
他はスクリーンショットの参照をお願いします。

### 現在のテキスト

Workspace settings

### スクリーンショット／動画

![postman-wsconfig](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/c54a4469-1d14-41d9-9e9e-0e2fcbcbd334)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。こちらはissue #24 と同じ内容ですので今後はそちらのissueで管理させていただきます。
こちらはクローズとさせていただきます。
