### ISSUE TITLE
Workspace infoダイアログ上のラベルが英語のままです

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#32]
### 問題の詳細

Workspaceの概要タブ上の ”Workspace Settings"右横の(i)をクリックすることで表示されるダイアログ内のラベルが英語のままです。

### 現在のテキスト

Workspace info

### スクリーンショット／動画

![wsinfo](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/42c780bb-ffb6-4214-b957-7574f64d5714)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘ありがとうございます。バグとして登録させていただきました、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
