### ISSUE TITLE
Workspace settings -> Visibilityのリスト値と説明が英語のままです

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#33]
### 問題の詳細

何も翻訳されていない状態です。
「現在のテキスト」には1つだけ入れておきます。
他はスクリーンショットの参照をお願いします。

これを#31とまとめて出すか悩んだのですが、とりあえず一つのスクリーンショットで表現できる単位で作成しました。
今後このようなパターンを一つにまとめた方が良い場合はお知らせください。

### 現在のテキスト

Personal

### スクリーンショット／動画

![ws-visibility](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/ee5564e0-f37f-45a4-963c-fcc0dc3d10e0)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘頂きありがとうございます！分かりやすくissueをわけてご説明いただき感謝いたします。
こちらにについては、#23, #24と同類のissueとしてそちらで管理させていただきます。

なお、これにともないこのissueはクローズとさせていただきます。
