### ISSUE TITLE
【ワークスペース削除】ダイアログの内藤が英語のまま

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#36]
### 問題の詳細

「Invite」ボタンのダイアログが翻訳済みなので、「Delete Workspace」のボタンも翻訳済みかと思ったら、まだ英語のままなのでIssueあげさせていただきます。

ステップ：
「ワークスペース」>「ワークスペース設定」> 「Delete Workspace」をクリック

### 現在のテキスト

"Delete workspace?",  "Everything {{workspace.name}} {{workspace.type}} workspace will be gone forever. Only collections can be restored from trash.", "Enter workspace name to confirm everyone in this workspace." "Cancel", "Delete Workspace"

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/5d5e90af-21f6-499e-b75e-710172a6a018)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-ui-231026-1128

### その他コメントやコンテキスト

#35 同様で、「Delete Workspace」のボタンを押す後のメッセージが英語のままです。
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/48ee5d1a-49fc-4b80-a5d5-062b74fbdfab)

**Comment by nagix** [comment]
次のアップデートで修正予定です。
