### ISSUE TITLE
モニターがまだ作成されていない場合の "You have no monitors ..." が英語のまま

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#37]
### 問題の詳細

タイトル通りです。スクリーンショットを参照願います。

### 現在のテキスト

You have no monitors

### スクリーンショット／動画

![monitor-general](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/426bf6e2-19ca-4a80-a7b3-5d3b1b6f8e01)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by nagix** [comment]
ご指摘ありがとうございます。[README](https://github.com/postmanlabs/postman-japanese-ea#%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)に記載の通り、「モニター」コンポーネントは現在日本語化の対象外になっております。一部日本語化が行われておりますが、この部分の作業はこれからとなりますのでご承知おきください。
