### ISSUE TITLE
consecutive failures の訳

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#38]
### 問題の詳細

[モニターを作成] 画面の [通知を停止する条件] にある "連続失敗” は失敗の回数のみに限定されているので、回数である事を明確にした訳にした方が良いと考えます。

### 現在の表記

連続失敗

### 提案する表記

回連続失敗

### スクリーンショット／動画

![consecutive-fail](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/ddb9fdd3-e850-47a1-a55b-8111f708436f)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by nagix** [comment]
ご提案ありがとうございます。ご指摘のとおり「回」が含まれているほうが分かりやすいと思います。次のバージョンにて「<入力欄> 回連続して失敗したら通知を停止」に変更予定です。
