### ISSUE TITLE
[このモニターの実行] のオプションリストが英語まま

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#39]
### 問題の詳細

[このモニターの実行] にある、リストが未翻訳です。
時間については、本来はローカル環境のLocaleを参照してほしいですが、現状のままでも良いとは思います。
もし、AM/PM  を午前/午後とするなら日本の表記にあわせて前に置くようにしてほしいですね。

### 現在のテキスト

Week timer

### スクリーンショット／動画

![monitor-options](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/7dcdf95b-25df-4112-82ea-d5bb959b95c7)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by nagix** [comment]
ご指摘ありがとうございます。[README](https://github.com/postmanlabs/postman-japanese-ea#%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)に記載の通り、「モニター」コンポーネントは現在日本語化の対象外になっております。一部日本語化が行われておりますが、この部分の作業はこれからとなりますのでご承知おきください。
