### ISSUE TITLE
Run this monitorの訳

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#40]
### 問題の詳細

今は直訳で、すぐに実行するような意味に見えるので、意訳で頻度を使う事を提案します。

### 現在の表記

このモニターの実行

### 提案する表記

モニターの実行頻度

### スクリーンショット／動画

![run-this-monitor](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/8e950ab0-5c16-432e-808a-1422769cc268)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by nagix** [comment]
ご提案ありがとうございます。ご指摘のとおり「モニターの実行頻度」とするほうが適切ですので、そのように変更予定です。
