### ISSUE TITLE
未保存警告が英語のまま

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#41]
### 問題の詳細

リクエストが未保存の状態でモードを切り替えようとすると警告ダイアログが表示されますが、これが英語のままです。
動画参照ねがいます。

### 現在のテキスト

Unsaved change

### スクリーンショット／動画

https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/9b6327c3-8e38-4d86-83aa-c4f63fd6d2ee

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。こちら期待どおりに日本語化されていないためバグとして登録させていただきました、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
バージョン10.20.0で修正済みです。
