### ISSUE TITLE
[クッキーを同期] 画面の警告&エラーが英語のまま

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#42]
### 問題の詳細

クッキー画面でのインターセプター/プロキシー オプションに対するエラー/警告が英語のままです。

環境としてブラウザー拡張が無い/postmanの証明書がない状態です。

### 現在のテキスト

No connection to interceptor

### スクリーンショット／動画

https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/c79d3002-82de-4d0b-969e-9d96546ee572

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by nagix** [comment]
バージョン10.20.0で修正済みです。
