### ISSUE TITLE
[ヘッダープリセットの管理] 画面の説明が不自然 

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#43]
### 問題の詳細

スクリーンショットに赤線引いてある
"あなたの は よく...”
"で 彼ら を"
の2箇所が不自然な日本語になっています。

※ スクリーンショット内の青枠部分は参考に英語のを貼ったまでで、実際の画面に出ているわけではありません。

### 現在のテキスト

them

### スクリーンショット／動画

![manage-header-preset](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/6261b9c0-89eb-42f3-a5bd-45c5bd1a64ab)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by nagix** [comment]
ご指摘ありがとうございます。現バージョンではこの部分は機械翻訳でしたが、こちらは次バージョンでは「ヘッダープリセットは、キーと値のペアとして格納されるヘッダーのグループです。これにより、よく使用するヘッダーを 1 つのプリセットに格納できるため、複数のリクエストで簡単に再利用することができます。」のように表示される予定です。
