### ISSUE TITLE
ワークスペースの概要ページに複数の未翻訳文

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#45]
### 問題の詳細

新規作成したワークスペースの概要ページに複数の未翻訳文字列があります。
ここに関連した画面のissueもあったので既に報告されているかと思って再チェックしたのですが、見当たらなかったのでissue作成しました。(見落としであればごめんなさい)

Workspace descriptionの箇所は自分で更新可能ですが初期値が英語なので、これも含めています。

### 現在のテキスト

Workspace descriptionなど

### スクリーンショット／動画

![workspace-general](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/ef410809-672e-402d-8e52-a7e32a7c398c)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。

Workspace descriptionの部分ですが、こちらはblack workspacesを選択した際のデフォルトテンプレートの問題であるため、こちらの issue https://github.com/postmanlabs/postman-japanese-ea/issues/22 にて管理させていただきます。

なお、下記テキストについては、既に翻訳対応がされており、近いリリースで修正予定となっているため、本件はクローズとさせていただきます。
- Contributors
- View workspace activities
- Pinned collections,  Make it easy to discover notable collections in this workspace by pinning them here
- Explore workspace templates

**Comment by rikosaita** [comment]
@yokawasa 
クローズされたissueに関わらずコメントして失礼します。
こちらのissueはPin Collectionの機能も含めますでしょうか？含めなければ新しいissue作成します。
1. コレクションなし (+) アイコンにマウスオーバーの説明 →　"Add Collections to this workspace to pin them."
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/d5682563-6e6f-4699-94eb-148b9f2978d2)

2. コレクションあり (+) アイコンをクリック → "Select Collection"
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/ab750d04-7efd-4320-9e3c-3f5d3a629436)

3. コレクションあり、環境なし、 (+) アイコンをクリック > コレクションを選択 → "No Environment", "Your workspace doesn’t have any environments yet."
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/903cb869-3e17-45fc-bcb7-fa59701b117e)

4. コレクションあり、環境あり → "Select an environment that you recommend for this collection."
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/911d0cde-bc23-41fc-a611-3e8477cebb0b)

5. 全部コレクションがピンされた後 (+) アイコンにマウスオーバーの説明 → "All Collections in this workspace are already pinned"
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/fb3c83cf-3b4e-4985-b07d-22672267fbec)

6. ３個ピンした後 (+) アイコンにマウスオーバーの説明 → "You can only pin 3 collections"
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/7729f189-a9b1-4908-ac55-5f891acda663)

7. ピン削除するのポップアップメッセージ → "Remove pin? Once removed the {{collection.name}} collection will no longer be pinned to the workspace overview.", "Cancel", "Remove"
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/400c85d6-c5bd-4ec3-8691-23a9a78ac613)

**Comment by yokawasa** [comment]
@rikosaita コメントありがとうございます。
説明足らずですいません。Pinned collectionsについては、環境選択、削除モーダル、エラーモーダル含めて既に翻訳対応がされていることを確認しているので、新しくissueを作成いただかなくても大丈夫です 🙇
