### ISSUE TITLE
未保存のタブをクローズする際の警告メッセージのタブ名が識別しにくい

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#47]
### 問題の詳細

英語では必然的に前後にスペースが入るのですが、日本語でスペース無しでタブ名をつなげると、ボールドになっていても語の切れ目がわかりにくいです。
- タブ名の前後にスペース (または[]) を入れて"このタブ **タブ名** には未保存の..."のようにする
- "このタブ"を削除し、"**タブ名**には未保存の..."とする
- 句読点を入れて "このタブ、**タブ名**には未保存の..."とする

などの形式にする事を提案します。

### 現在のテキスト

This tab tabname has...

### スクリーンショット／動画

![tab-unsave-warn](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/8b3308f5-c58c-4592-8dfc-0cf5db7a5d19)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.19.10

**Comment by yokawasa** [comment]
ご提案いただきありがとうございます。内容について確認させていただきます。方針が決まり次第ご連絡します

**Comment by nagix** [comment]
タブ名の前後にスペースを入れるように修正予定です。
