### ISSUE TITLE
【ワークスペース】【コレクション】ウオッチャーのラベルがまだ英語のまま

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#48]
### 問題の詳細

重複のissueでしたらすみません。
ワークスペースとコレクションでのウオッチャーが英語のまま状態です。

### 現在のテキスト

"No watchers People who watch this Workspace will show up here.", "No watchers People who watch this collection will show up here.", "1 watcher", "2 watchers", "(You)"

### スクリーンショット／動画

1. ワークスペースにてウオッチャーが0人
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/0a418025-ce5b-4596-b1d0-c720f02918ec)

2. ワークスペースにてウオッチャーが1人 (コレクション同様)
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/fbbded29-10a9-4f1f-961d-cd15c6fd7245)

3. ワークスペースにてウオッチャーが2人以上 (コレクション同様)
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/d7359dd9-751e-4558-b33c-dad8517366c8)

5. ワークスペースにてウオッチャーが0人
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/de7f68c8-1f41-4b75-9087-7d71ffb7e386)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-ui-231026-1128

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。こちらバグとして登録させていただきました。なにか更新がありましたら本issueスレッドでご連絡します

**Comment by nagix** [comment]
次のアップデートで修正予定です。
