### ISSUE TITLE
【ワークスペース】ヘッダーにあるアバターの関連で表示が英語のまま

### ISSUE THREAD

**Issue by rikosaita** [postmanlabs/postman-japanese-ea#49]
### 問題の詳細

1. 自分のアバターにマウスオーバーすると"You"が表示され、
2. 自分以外のアバターはLast Activeの時間表示されるが、英語の"minutes"だったりする
3. アバターをクリックすると全ユーザーのアクティブ時間表示され、"minutes ago"表示されている

### 現在のテキスト

"You","Visited 17 minutes ago"

### スクリーンショット／動画

1. ![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/ecbb083d-3171-426d-93a8-7ec30ce82ae4)

2. ![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/1c0e8628-d742-4f77-89ba-d6772d02bf43)

3. ![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/a8f21def-19aa-4005-b1aa-cc0862160dea)

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.19.10-ui-231026-1128

### その他コメントやコンテキスト

スクリーンショットには"minutes"が表示されていますが、時間、日付、月、年などの表示方法が確認できない部分があります。

**Comment by rikosaita** [comment]
「ワークスペース一覧」でも自分のアバターにマウスオーバーすると"You"が表示されてしまう。
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/8726064/1fbac13e-2543-4840-94d1-3ea1011447b9)

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。こちらバグとして登録させていただきました。更新ありましたらこちらにご連絡します

**Comment by nagix** [comment]
次のアップデートで修正予定です。

**Comment by nagix** [comment]
v10.22.0でヘッダーメニューの日本語表示に対応しました。ワークスペース一覧のアバターのツールチップは対応中です。
