### ISSUE TITLE
"RAW" は "未加工" とせず、"RAW" のままの方がわかりやすい

### ISSUE THREAD

**Issue by s0hide** [postmanlabs/postman-japanese-ea#5]
### 問題の詳細

"RAW" は "未加工" とせず、"RAW" のままの方がわかりやすいと思います。

### 現在の表記

未加工

### 提案する表記

RAW

### スクリーンショット／動画

<img width="601" alt="スクリーンショット 2023-10-25 21 49 09" src="https://github.com/postmanlabs/postman-japanese-ea/assets/144641648/03d0fa2b-c1b7-41d4-a121-37c4ffdb6ee7">

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.6-231017-0734

**Comment by nagix** [comment]
ご提案ありがとうございます。ご指摘のとおり「RAW」表記がわかりやすそうであるため、異論がなければそのように変更したいと思います。
