### ISSUE TITLE
【リクエスト】Form-dataのフィールドタイプのドロップダウンはラッピングしすぎ

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-japanese-ea#51]
### 問題の詳細

リクエストの「ボディ」の「form-data」のデータタイプに、「キー」のドロップダウンをクリックすると、選択肢のレイアウトはラッピングしすぎて読みづらいです

実際には、２つの選択肢があるはずです：
- テキスト
- ファイル

### 再現ステップ

１．新規リクエストを作成
２．「ボディ」タブに、「form-data」のデータタイプを選択
３．「キー」のところにマウスをホバーし、ドロップダウンを開く

### スクリーンショット／動画

<img width="793" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/4758a943-6795-4952-b369-63c222a77331">

### Postman プラットフォーム

両方

### オペレーティング システム

MacOS

### Postman バージョン

10.20.0-231018-1251

**Comment by nagix** [comment]
ご指摘ありがとうございます。バグ登録をしましたので、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
修正が完了しました。
