### ISSUE TITLE
[ワークスペース] インポート画面の翻訳が未完全

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-japanese-ea#52]
### 問題の詳細

![Screenshot 2023-11-14 at 1 29 03 pm](https://github.com/postmanlabs/postman-japanese-ea/assets/55820883/cc99c5e3-33f9-4344-8968-b8741c74700e)

### 再現ステップ

1. ワークスペースを開く
2. インポートCTAをクリックする

### スクリーンショット／動画

上記参照

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.20.0

**Comment by nagix** [comment]
ご指摘いただきありがとうございます。こちらはissue https://github.com/postmanlabs/postman-japanese-ea/issues/19 と同じ内容ですので今後はそちらのissueで管理させていただきます。
こちらはクローズとさせていただきます。
