### ISSUE TITLE
[チームドロップダウン] Billingに対応して「請求」が使われているがもう少しソフトな用語を提案します

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-japanese-ea#53]
### 問題の詳細

![Screenshot 2023-11-14 at 1 19 24 pm](https://github.com/postmanlabs/postman-japanese-ea/assets/55820883/1bb64a3b-53c7-47c1-8aa9-054931517ee5)

元の英語"Billing"に対して「請求」となっているが、日本語的に少し直接的すぎる表現なので、少しソフトに言い換えた方が良いと思います。

### 現在の表記

請求

### 提案する表記

お支払い管理

### スクリーンショット／動画

上記参照

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.12.0

**Comment by nagix** [comment]
ご提案ありがとうございます。この「請求」メニュー項目のリンク先の「Billing Overview」には「Plan and Payments」と「Resource usage」の2つのサブ項目があり、「お支払い」だとBillingが指す範囲よりも狭くなってしまいます。一方で、「請求」はメニュー選択による請求のアクションを想起してしまうため、情報の閲覧を示す意図で「請求情報」と変更したいと思います。
