### ISSUE TITLE
【ワークスペース】並び順名称の提案(AからZ)

### ISSUE THREAD

**Issue by TomiGie** [postmanlabs/postman-japanese-ea#54]
### 問題の詳細

すべてのワークスペースの一覧画面にて
並び順の項目のAからZという項目がありますが
次の文言にすると馴染み深いような気がします

### 現在の表記

AからZ

### 提案する表記

名前(昇順) or アルファベット(昇順)

### スクリーンショット／動画

<img width="965" alt="Screenshot 2023-11-16 at 10 40 07" src="https://github.com/postmanlabs/postman-japanese-ea/assets/11865327/9a3ccc52-5191-41bc-9326-f5b4d7559bb8">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.20.0

**Comment by yokawasa** [comment]
ご提案ありがとうございます。こちら確認させていただきます

**Comment by nagix** [comment]
ご指摘のとおり、「AからZ」というのは自然ではありませんので、シンプルに「名前」と変更する予定です。アルファベットだけでなくカナ・漢字も含まれ、読みは考慮されない順番になるため、「アルファベット」は適切でなく、また昇順/降順を切り替えられるわけでもないので(昇順)の表示は無しとします。
