### ISSUE TITLE
【ワークスペース】作成者の絞り込み表示ウィンドウ内の日本語化(Search)

### ISSUE THREAD

**Issue by TomiGie** [postmanlabs/postman-japanese-ea#57]
### 問題の詳細

ワークスペース一覧画面にて、「作成者」をクリックした際に表示されるウィンドウ内の文言で英語の部分がありましたので、日本語化の提案になります

### 現在の表記

Search

### 提案する表記

検索

### スクリーンショット／動画

<img width="584" alt="Screenshot 2023-11-16 at 12 06 02 copy" src="https://github.com/postmanlabs/postman-japanese-ea/assets/11865327/8900fc28-8ee4-4826-916d-afe666f107ec">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.20.0

**Comment by TomiGie** [comment]
翻訳が存在しない の方のテンプレートで作成するべきでしたね、すみません。

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。
~~こちらは、https://github.com/postmanlabs/postman-japanese-ea/issues/46 と重複となります。そちらのIssueにて管理させていただきます。~~

訂正です。こちら別issueですので、バグとして登録させていただきます。

**Comment by yokawasa** [comment]
たびたびすいません。 
https://github.com/postmanlabs/postman-japanese-ea/issues/28 との重複になりますので、そちらのissueにて管理させていただきます。
