### ISSUE TITLE
【ワークスペース】作成者の絞り込み表示ウィンドウ内の日本語化(Clear selected)

### ISSUE THREAD

**Issue by TomiGie** [postmanlabs/postman-japanese-ea#58]
### 問題の詳細

ワークスペース一覧画面にて、「作成者」をクリックした際に表示されるウィンドウ内の文言で英語の部分がありましたので、日本語化の提案になります

### 現在のテキスト

Clear selected

### スクリーンショット／動画

<img width="584" alt="Screenshot 2023-11-16 at 12 06 02" src="https://github.com/postmanlabs/postman-japanese-ea/assets/11865327/6476a0f5-48b6-4c0f-9b0a-d190c5cd1f09">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.20.0

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。
こちらは、 https://github.com/postmanlabs/postman-japanese-ea/issues/28 との重複になりますので、そちらのissueにて管理させていただきます。
