### ISSUE TITLE
【ワークスペースを作成】Blank Workspaceを作成すると開かれるページが英語のまま

### ISSUE THREAD

**Issue by Shigeki-Nagaya** [postmanlabs/postman-japanese-ea#59]
### 問題の詳細

画面を添付しました

### 現在のテキスト

Blank workspace Customize this space to organize and share your API resources with your team. Blank workspace workspace template preview Showcase your API’s capabilities icon Showcase your API’s capabilities Use Postman collections to document your APIs with ease. You can create your own or choose from 70+ collection templates tailored to your needs. Build together, work faster icon Build together, work faster Help your team maintain a shared source of truth, to build APIs and solve problems together.

### スクリーンショット／動画

![スクリーンショット 2023-11-17 15 33 48](https://github.com/postmanlabs/postman-japanese-ea/assets/50352194/cccf2335-1ca0-47b2-a39b-739c5e445789)

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

13.6

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。
Blank Worksapceが翻訳されていない件については、デフォルトテンプレートの問題であるため、こちらの issue https://github.com/postmanlabs/postman-japanese-ea/issues/22 にて管理させていただきます。
よって本 issueはクローズとさせていただきます。
