### ISSUE TITLE
Trashの訳について

### ISSUE THREAD

**Issue by rmukai-715** [postmanlabs/postman-japanese-ea#6]
### 問題の詳細

Trash → ごみ で直訳なのは理解できますが、感覚的には「ごみ箱」 の方が日本人にはしっくり来るかなと思いました。

### 現在の表記

ごみ

### 提案する表記

ごみ箱

### スクリーンショット／動画

![trash](https://github.com/postmanlabs/postman-japanese-ea/assets/75108502/2c8fbef7-8db1-485a-8001-9e91f9e16242)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.7

**Comment by nagix** [comment]
ご提案ありがとうございます。ご指摘のとおり「ごみ箱」表記が自然ですので、そのように変更予定です。
