### ISSUE TITLE
【環境】グローバルの説明文が一部タイポしている

### ISSUE THREAD

**Issue by TomiGie** [postmanlabs/postman-japanese-ea#60]
### 問題の詳細

環境＞グローバルを選択して表示される画面に、グローバル変数の説明文があるのですが、説明文内の「グローバル」のテキストが「グルーバル」とタイポになっているようです

### 現在のテキスト

ワークスペースのグルーバル変数は...

### スクリーンショット／動画

<img width="1490" alt="Screenshot 2023-11-16 at 20 52 34" src="https://github.com/postmanlabs/postman-japanese-ea/assets/11865327/1cc0a7a6-e192-4073-999f-8bc087caacc9">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.20.0

**Comment by nagix** [comment]
ご指摘ありがとうございます。次回のアップデートで修正予定です。
