### ISSUE TITLE
【環境】変数のタイプをシークレット→デフォルトにした時に表示されるダイアログの日本語表示

### ISSUE THREAD

**Issue by TomiGie** [postmanlabs/postman-japanese-ea#61]
### 問題の詳細

変数のタイプをシークレット→デフォルトにした時に表示されるダイアログの日本語が少し不自然な気がしました。

- 「これにより..」から始まる説明文の中盤あたりに「あなたの がローカルで...」という表記があり、日本語の構文として不自然な状態になっています
- 「もう1度聞かないでください」のチェックボックスの文言は「再度表示しない」などにしたほうが自然な気がしました
- 変更ボタンのテキストが「タイプの変更」となっていますが、シンプルに「変更する」の方が自然な気がしました

### 現在のテキスト

問題の詳細にて記載しましたので、そちらを参照ください

### スクリーンショット／動画

<img width="432" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/11865327/ad3d8acf-c1ab-43f6-b81e-b07296135d7d">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.20.0

**Comment by nagix** [comment]
ご指摘ありがとうございます。こちらのダイアログはアイコン表示の不具合もあり、バグ登録をしましたので、更新情報がありましたらお知らせします。表記については次の通りです。

- 「これにより..」: 「この操作を行うと、マスクされた値がすべてのチームメンバーのアプリでプレーンテキストとして表示されるようになります。ローカルで自分向けに値のマスクを解除したい場合は、行の末尾にあるアイコンを使用してください。」に変更予定です
- 「もう一度聞かないでください」: 「再度表示しない」に変更予定です
- 「タイプの変更」: 英語に基づき「タイプ」は残しますが、操作の意図を明確にするため「タイプを変更」に変更予定です

**Comment by nagix** [comment]
バグについても次のアップデートで修正予定です。
