### ISSUE TITLE
【コレクション】実行＞機能タブの件数指定のデフォルトが英語のままになっている

### ISSUE THREAD

**Issue by TomiGie** [postmanlabs/postman-japanese-ea#62]
### 問題の詳細

コレクション＞実行＞機能タブを表示したデフォルトの状態では、件数選択のプルダウンのテキストが `Last 100 runs` と英語になっている。

一度プルダウンを開いて 最新の100実行 を選択し直すと、ウィンドウを閉じて再度この画面に戻ってきても日本語のままになっている

### 現在のテキスト

Last 100 runs

### スクリーンショット／動画

![2023-11-18 01 38 16](https://github.com/postmanlabs/postman-japanese-ea/assets/11865327/2db5093a-a3fe-4040-bb1f-57fdda96f21e)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.20.0

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。こちらバグとして登録しました。また更新がありましたらお知らせします 🙇‍♂️

**Comment by nagix** [comment]
次のアップデートで修正予定です。
