### ISSUE TITLE
[ドメインを追加]の文字の折り返し位置が不自然

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#63]
### 問題の詳細

翻訳あるあるですが、ボタンの幅が足りない為に[ドメインを追加]が不自然な折り返しになっています。
以下の2つの対策を提案させていただきます。

A. 翻訳文字列を "ドメインを\r追加"のようにして強制的に折り返す
B. ボタンの幅を広げる ( = [ドメイン]のテキストボックスを縮める)
C. 翻訳を"追加"のみにする

### 再現ステップ

スクリーンショット参照

### スクリーンショット／動画

![postman add domain btn](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/8386d1ee-42db-4e64-9cee-d16a06ccb5e7)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.20.0

**Comment by yokawasa** [comment]
ご指摘、ご提案ありがとうございます。こちら事象については確認できました。
対応方針については検討させていただきます。一旦、ステータスを確認中とさせていただきます

**Comment by yokawasa** [comment]
ステータスをバグとしました。更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
