### ISSUE TITLE
翻訳の提案 -> "このプロキシには認証が必要です"

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#65]
### 問題の詳細

コレクション -> いずれかのタブ -> 設定-> プロキシの "このプロキシには認証が必要です" はユーザーに対するメッセージのように見えてしまうので、オプションのラベルとして "認証が必要なプロキシ" のような言い切り型の表現にする事を提案します。

### 現在の表記

このプロキシには認証が必要です

### 提案する表記

認証が必要なプロキシ

### スクリーンショット／動画

![postman proxy authopt](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/0eea1c7d-336a-42de-9f5d-ff2c4cb827d1)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.20.0

**Comment by nagix** [comment]
ご提案ありがとうございます。ご指摘のとおり、プロキシに対する設定かユーザーに対する指示かが曖昧ですので、より結果が明確な「このプロキシでは認証を必須とする」という表記に変更する予定です。
