### ISSUE TITLE
リクエストの設定 -> Default:設定 のラベルが、リクエスト作成時の言語で固定されている

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#66]
### 問題の詳細

英語で作成した場合は "Default: Settings” は日本語に切り替えても "デフォルト: Settings"となり、日本語で作成した場合は英語に切り替えても”Default: 設定” となってしまう。

説明だけではわかりにくいので、添付の動画で確認をお願いします。

### 再現ステップ

動画参照

### スクリーンショット／動画

https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/e15f4aac-38d9-4d44-a9a4-1a4bb700ac7d

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.20.0

**Comment by yokawasa** [comment]
ご指摘いただきありがとうございます。こちらバグとしてしました。また更新がありましたらご連絡いたします

**Comment by nagix** [comment]
次のアップデートで修正予定です。
