### ISSUE TITLE
誤訳 "Get notified on Slack"

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#67]
### 問題の詳細

"on Slack"に対する誤訳と思われます。

### 現在の表記

Slackに関する通知を受け取る

### 提案する表記

通知をSlackで受け取る

### スクリーンショット／動画

![postman slack](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/1e5f5aba-ebee-4b0a-949b-2c11b973be2b)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.20.0

**Comment by yokawasa** [comment]
ご指摘ありがとうございます。こちらバグ登録させていただきました。また更新がありましたらおしらせします。

**Comment by yokawasa** [comment]
`Slackで通知を受け取る` としました。今後のアップデートで反映される予定です。
ご提案いただきありがとうございました。
