### ISSUE TITLE
翻訳の提案 -> "親の認証設定を継承する”

### ISSUE THREAD

**Issue by batgh** [postmanlabs/postman-japanese-ea#68]
### 問題の詳細

Authenticationの "Inherit auth from parent" が "親の認証設定を継承する" となっていますが、ここはリスト値なので ”する” は不要だと考えます。
また、parent に関しては、フォルダー/コレクションが明示されていないので、個人的には「上位」という表現の方がしっくり来ます。

### 現在の表記

親の認証設定を継承する

### 提案する表記

上位の認証設定を継承 / 親の認証設定を継承

### スクリーンショット／動画

![postman inherit](https://github.com/postmanlabs/postman-japanese-ea/assets/2231326/d43a044d-52e7-4208-9a9f-a36e04cfa861)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Mac

### Postman バージョン

10.20.0

### その他コメントやコンテキスト

以前、コミュニティで回答いただいた英文字前後の空白を入れないルールについては、いくつかの選択肢（や他の画面でも）に空白が入っているものに気づいていますが、スタイルに関しては後でまとめて修正されるとの事なのでissueは作成していません。

**Comment by yokawasa** [comment]
ご提案ありがとうございます。こちら検討させていただきます。ステータスを一旦確認としました

**Comment by yokawasa** [comment]
`上位の認証設定を継承` をとさせていただきます。今後のアップデートで更新される予定ですので本件をクローズとさせていただきます。
ご提案いただきありがとうございました。
