### ISSUE TITLE
チーム設立時のトグルボタン操作時のメッセージ

### ISSUE THREAD

**Issue by kurunkobe** [postmanlabs/postman-japanese-ea#69]
### 問題の詳細

※翻訳のスコープ対象外とは認識しておりますが、操作と矛盾する表記であるため報告させていただきました。

■操作手順
手順①：「あなたのチームを設立する」の画面に遷移します。
手順②：「チームディスカバリ」項目にあるトグルスイッチを ON→OFF に操作します。

■問題点
OFF操作したにも関わらず、メッセージが「有効にしました」と表示されます。

### 現在のテキスト

あなたのチームのチームディスカバリを有効にしました

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/151384575/fe650fb1-c58a-492c-8ee0-c3cb5ba233d1)

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

Windows

### Postman バージョン

10.20.3-231120-0418

### その他コメントやコンテキスト

スコープ対象外ですので正確な翻訳の途中かとは思いますが、
取り急ぎ「無効にしました」とするのが良いかなと思いました。

**Comment by nagix** [comment]
ご指摘ありがとうございます。こちらは英語版を含めてメッセージが間違っており、バグ登録をいたしました。更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
