### ISSUE TITLE
メニューバーの日本語化

### ISSUE THREAD

**Issue by rmukai-715** [postmanlabs/postman-japanese-ea#7]
### 問題の詳細

macOS版のPostmanで、メニューバーが英語表記のままです。
本体部分は技術用語も多いので英語の方が分かりやすい部分もありますが、メニューバーの内容は全て日本語になったほうが良いかと思いました。

### 現在の表記

File Edit View Window Help

### 提案する表記

ファイル 編集 表示 ウィンドウ ヘルプ

### スクリーンショット／動画

![スクリーンショット 2023-10-26 7 30 46](https://github.com/postmanlabs/postman-japanese-ea/assets/75108502/449f7872-73d4-401e-a95f-d0f3e5228146)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.7

**Comment by nagix** [comment]
ご指摘ありがとうございます。Mac 版のメニューバーの日本語化も進めておりますので、近々日本語で表示される予定です。

**Comment by nagix** [comment]
v10.22.0でOSメニューの日本語表示に対応しました。「ウィンドウ」メニューの一部のメニュー項目が英語表示のままですが、対応を予定しています。
