### ISSUE TITLE
【コレクション】未保存のタブを閉じる操作したときのメッセージ

### ISSUE THREAD

**Issue by kurunkobe** [postmanlabs/postman-japanese-ea#70]
### 問題の詳細

■操作手順
手順①：コレクションの一覧表示から任意のリクエストを選択し、リクエストの画面（新規のタブ）が表示されたのを確認。
手順②：リクエスト画面内でURLを入力するなどの操作を行い、タブの右側に「●」の表示がされるのを確認。
手順③：タブの「×」をクリックし、その後に表示されるメッセージを確認する。

■問題点
「保存しますか？」ウィンドウ内の✅チェックボックスの説明文
「タブを閉じるときに変更を保存するように求められることはなくなりました。」
は、まだ実行前であることから違和感があります。
（スクリーンショット内の黄色下線部）

### 現在のテキスト

求められることはなくなりました。

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/151384575/b16e78c9-ef85-43f8-bde7-c990b47260a5)

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

Windows

### Postman バージョン

10.20.3-231120-0418

### その他コメントやコンテキスト

「なくなりました。」→「なくなります。」
が良いかなと思います。

**Comment by kurunkobe** [comment]
グローバル変数を編集し、「×」操作したときも同様のメッセージが表示されますので合わせて報告致します。
![image](https://github.com/postmanlabs/postman-japanese-ea/assets/151384575/dda69fec-c183-443c-bf5a-164cfe1044f8)

**Comment by nagix** [comment]
ご提案ありがとうございます。ご指摘のとおり「求められなくなります。」という表記が自然ですので、そのように変更予定です。
