### ISSUE TITLE
【コレクション】テスト結果の合否表示

### ISSUE THREAD

**Issue by kurunkobe** [postmanlabs/postman-japanese-ea#72]
### 問題の詳細

■操作手順
手順①：コレクションからリクエストを開きます。
手順②：テストに失敗系スクリプトを入力し、「送信」ボタンを押下します。

■問題点
成功時は「合格」の表記ですが、失敗時は「失敗する」と表記されており違和感があります。
（スクリーンショット内の黄色枠部）

### 現在のテキスト

失敗する

### スクリーンショット／動画

![image](https://github.com/postmanlabs/postman-japanese-ea/assets/151384575/fbd9caec-94b5-4082-af96-5d233bfc2b30)

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

Windows

### Postman バージョン

10.20.7

### その他コメントやコンテキスト

上部の絞り込みボタンに「失敗」とありますので、同様に「失敗」が良いかなと思います。

**Comment by nagix** [comment]
ご提案ありがとうございます。ご指摘のとおり「失敗」表記が自然ですので、そのように変更予定です。
