### ISSUE TITLE
[ワークスペース設定]「招待」の文字のオリエンテーションが縦向き

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-japanese-ea#73]
### 問題の詳細

「招待」の文字のオリエンテーションが縦向きになっているため、ボタンからはみ出ている。

### 再現ステップ

ワークスペース設定画面を開く

### スクリーンショット／動画

<img width="507" alt="Screenshot 2023-12-06 at 11 15 12 am" src="https://github.com/postmanlabs/postman-japanese-ea/assets/55820883/458adbae-71e8-439f-a752-7a9b1b64347c">

### Postman プラットフォーム

両方

### オペレーティング システム

macOS

### Postman バージョン

10.20.10

**Comment by nagix** [comment]
ご指摘ありがとうございます。バグ登録をしましたので、更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
