### ISSUE TITLE
ツールバーメニューの文字が文字化けする

### ISSUE THREAD

**Issue by cm-kazup0n** [postmanlabs/postman-japanese-ea#77]
### 問題の詳細

添付の通り、メニューバーの文字が化けています。

英語表示にすると発生しません

### 再現ステップ

1. Postman Appを起動する

### スクリーンショット／動画

<img width="506" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/29879544/9f0315ff-e2a7-4b60-8535-591f95144ee4">
<img width="629" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/29879544/7e1e6e32-f005-49c3-9113-e313a5a74113">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS 14.2（23C64）

### Postman バージョン

10.21.4

### その他のコメントやコンテキスト

Version 10.21.4
UI Version: 10.21.4-ui-231215-1047
Desktop Platform Version: 10.21.0 (10.21.0)

**Comment by nagix** [comment]
ご指摘ありがとうございます。すでにバグ登録がされており、修正対応中です。更新情報がありましたらお知らせします。

**Comment by nagix** [comment]
次のアップデートで修正予定です。
