### ISSUE TITLE
【文字化け】デスクトップアプリのメニューが文字化けになっている

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-japanese-ea#79]
### 問題の詳細

下記のデスクトップ環境で、UIが日本語に設定している場合、Postmanの上のメニューが文字化けになっているようです

<img width="917" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/18d0c84c-495c-4284-ab7d-91c554a9b2c7">

<img width="1183" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/91e16fde-d64c-4abb-8d1e-8a392de08c1b">

なお、UIが英語に設定している場合、通常の表示が出るらしいです
<img width="928" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/e6198e0f-a9df-46e2-a01d-950dd3b9fdff">

### 再現ステップ

（ユーザーからの報告なので、再現方法ははっきりわかりません）

下記のデスクトップ環境でPostmanを開く

### スクリーンショット／動画

<img width="917" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/18d0c84c-495c-4284-ab7d-91c554a9b2c7">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

MacOS

### Postman バージョン

10.21.11

### その他のコメントやコンテキスト

<img width="318" alt="image" src="https://github.com/postmanlabs/postman-japanese-ea/assets/9841162/6c409300-5775-4c65-99c5-f06379a13375">

**Comment by nagix** [comment]
ご指摘いただきありがとうございます。こちらはissue https://github.com/postmanlabs/postman-japanese-ea/issues/77 と同じ内容ですので今後はそちらのissueで管理させていただきます。
こちらはクローズとさせていただきます。
