### ISSUE TITLE
Params の和訳

### ISSUE THREAD

**Issue by s0hide** [postmanlabs/postman-japanese-ea#8]
### 問題の詳細

Params の和訳は、
変数、あるいは Params のままの方が良いのでは。
スニペットの説明では、Params は、変数と和訳されているように見えます。

### 現在の表記

パラメーター

### 提案する表記

変数  （または Params のまま）

### スクリーンショット／動画

<img width="1609" alt="スクリーンショット 2023-10-26 16 38 40" src="https://github.com/postmanlabs/postman-japanese-ea/assets/144641648/1f8e0353-f5ce-4bf9-bceb-6b8727b58ffb">

### Postman プラットフォーム

Postman ウェブアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.9-231025-0520

**Comment by nagix** [comment]
ご提案ありがとうございます。クエリパラメーター、パスパラメーターなどの用語は一般的に使われているため、「パラメーター」という用語を使用する方針で考えています。なお、変数はPostman内でVeriablesを指すために使われているため、ここでは混乱を避けるため使わない方針です。
