### ISSUE TITLE
Pre-request Script の和訳

### ISSUE THREAD

**Issue by s0hide** [postmanlabs/postman-japanese-ea#9]
### 問題の詳細

Pre-request Script  の訳は
プレリクエストスクリプト
ではなく
前処理 Script
はどうでしょうか。

### 現在の表記

プレリクエストスクリプト

### 提案する表記

前処理 Script

### スクリーンショット／動画

<img width="1609" alt="スクリーンショット 2023-10-26 16 38 40" src="https://github.com/postmanlabs/postman-japanese-ea/assets/144641648/c6021bd1-49cb-4d36-af14-62a6d3c5f7fb">

### Postman プラットフォーム

Postman デスクトップアプリ

### オペレーティング システム

macOS

### Postman バージョン

10.19.9-231025-0520

**Comment by nagix** [comment]
ご提案ありがとうございます。Pre-requestを前処理とした場合、スクリプトが実行されるタイミングがどの処理の前になるかが曖昧になってしまうため、英語をそのままカタカナにした「プレリクエストスクリプト」を使用する方針で考えています。
